import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AppProviders } from '@/lib/providers';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import {Poppins} from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',

  
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gray-100`}
      >
        {/* Include  all Providers in file '@/lib/providers.tsx' insead of here */}
        <AppProviders>
          <Header />
          {children}
          <Footer />

        </AppProviders>
      </body>
    </html>
  );
}
